import { onSchedule } from "firebase-functions/v2/scheduler";
import * as logger from "firebase-functions/logger";
import { defineSecret } from "firebase-functions/params";
import sgMail = require("@sendgrid/mail");
import { findFallingStocks, StockDropResult } from "./scanner";
import { scanRsiStrategy, scanGoldenCrossStrategy, RsiResult, GoldenCrossResult } from "./strategies";

const sendGridApiKey = defineSecret("SENDGRID_API_KEY");

export const dailyStockScan = onSchedule(
  {
    schedule: "every monday,tuesday,wednesday,thursday,friday 08:00",
    timeZone: "Asia/Kolkata",
    secrets: [sendGridApiKey],
    timeoutSeconds: 540, // 9 minutes
    memory: "1GiB",
  },
  async (event) => {
    logger.info("Starting daily stock scan...");
    
    try {
        const [fallingStocks, rsiStocks, goldenCrossStocks] = await Promise.all([
          findFallingStocks(),
          scanRsiStrategy(),
          scanGoldenCrossStrategy()
        ]);

        const totalAlerts = fallingStocks.length + rsiStocks.length + goldenCrossStocks.length;
        
        if (totalAlerts === 0) {
            logger.info("No stocks found matching any criteria.");
            return;
        }

        logger.info(`Found ${totalAlerts} total alerts. Sending email...`);
        
        sgMail.setApiKey(sendGridApiKey.value());

        const msg = {
          to: "sivanandi9073@gmail.com",
          from: "smurugesapillai@perchenergy.com",
          subject: `Stock Alert: ${totalAlerts} Opportunities Found`,
          html: generateComprehensiveEmail(fallingStocks, rsiStocks, goldenCrossStocks),
        };

        await sgMail.send(msg);
        logger.info("Email sent successfully.");

    } catch (error) {
        logger.error("Error in dailyStockScan:", error);
    }
  }
);

function generateComprehensiveEmail(
    falling: StockDropResult[], 
    rsi: RsiResult[], 
    gc: GoldenCrossResult[]
): string {
    
    const fallingTable = falling.length ? generateFallingTable(falling) : '<p>No stocks falling >6% detected.</p>';
    const rsiTable = rsi.length ? generateRsiTable(rsi) : '<p>No RSI opportunities detected.</p>';
    const gcTable = gc.length ? generateGcTable(gc) : '<p>No Golden Crosses detected today.</p>';

    return `
        <div style="font-family: Arial, sans-serif; color: #333;">
            <h1 style="color: #2c3e50;">Daily Market Scanner Results</h1>
            <p>Here is your automated improved daily report.</p>
            <hr />
            
            <h2 style="color: #c0392b;">1. Falling Knives (>6% Drop)</h2>
            ${fallingTable}
            
            <br />
            <h2 style="color: #2980b9;">2. RSI Reversion Candidates</h2>
            ${rsiTable}
            
            <br />
            <h2 style="color: #f39c12;">3. Golden Cross (Trend Reversal)</h2>
            ${gcTable}
            
            <br />
            <p style="font-size: 12px; color: #777;">Generated by Firebase Cloud Functions. Data from Yahoo Finance.</p>
        </div>
    `;
}

function generateFallingTable(stocks: StockDropResult[]): string {
    const rows = stocks.map(s => `
        <tr>
            <td><b>${s.symbol}</b></td>
            <td>${s.currentPrice.toFixed(2)}</td>
            <td>${s.referencePrice.toFixed(2)}</td>
            <td style="color: red; font-weight: bold;">${s.dropPercentage}%</td>
            <td>${s.referenceDate}</td>
        </tr>
    `).join('');

    return `
        <table border="1" cellpadding="8" cellspacing="0" style="border-collapse: collapse; width: 100%; border-color: #ddd;">
            <thead>
                <tr style="background-color: #f2f2f2;">
                    <th>Symbol</th>
                    <th>Price</th>
                    <th>Ref Price</th>
                    <th>Drop %</th>
                    <th>Ref Date</th>
                </tr>
            </thead>
            <tbody>${rows}</tbody>
        </table>
    `;
}

function generateRsiTable(stocks: RsiResult[]): string {
    const rows = stocks.map(s => {
        const isHighQuality = s.trend === 'OVERSOLD_IN_UPTREND';
        const rowStyle = isHighQuality ? 'background-color: #d4edda;' : ''; // Light green background
        const trendLabel = isHighQuality ? `<strong>${s.trend.replace(/_/g, ' ')} ⭐</strong>` : s.trend.replace(/_/g, ' ');

        return `
        <tr style="${rowStyle}">
            <td><b>${s.symbol}</b></td>
            <td>${s.currentPrice.toFixed(2)}</td>
            <td style="font-weight: bold; color: ${s.trend.startsWith('OVERSOLD') ? 'green' : 'red'};">${s.rsi.toFixed(2)}</td>
            <td>${trendLabel}</td>
        </tr>
    `}).join('');

    return `
        <table border="1" cellpadding="8" cellspacing="0" style="border-collapse: collapse; width: 100%; border-color: #ddd;">
            <thead>
                <tr style="background-color: #f2f2f2;">
                    <th>Symbol</th>
                    <th>Price</th>
                    <th>RSI (14)</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>${rows}</tbody>
        </table>
    `;
}

function generateGcTable(stocks: GoldenCrossResult[]): string {
    const rows = stocks.map(s => {
        const rsiColor = s.rsi > 70 ? 'red' : 'green';
        return `
        <tr>
            <td><b>${s.symbol}</b></td>
            <td>${s.currentPrice.toFixed(2)}</td>
            <td style="font-weight: bold; color: ${rsiColor}">${s.rsi.toFixed(2)}</td>
            <td>${s.ma50.toFixed(2)}</td>
            <td>${s.ma200.toFixed(2)}</td>
            <td style="color: gold; font-weight: bold; background-color: #444;">GOLDEN CROSS</td>
        </tr>
    `}).join('');

    return `
        <table border="1" cellpadding="8" cellspacing="0" style="border-collapse: collapse; width: 100%; border-color: #ddd;">
            <thead>
                <tr style="background-color: #f2f2f2;">
                    <th>Symbol</th>
                    <th>Price</th>
                    <th>RSI (14)</th>
                    <th>50 SMA</th>
                    <th>200 SMA</th>
                    <th>Signal</th>
                </tr>
            </thead>
            <tbody>${rows}</tbody>
        </table>
    `;
}
